[profile.default]
src = "src"
out = "out"
ffi = false
via_ir = false

libs = ["lib"]

[[profile.default.fs_permissions]]
access = 'read'
path = 'script/input'

[etherscan]
base-sepolia = { key = "api-key" }
base = { key = "api-key" }

[profile.test]
env = ".env.testing"